title: "Fémur Corto Congénito"
description: "Información, experiencias y recursos sobre el Fémur Corto Congénito"
lang: es

url: "https://albertorp.github.io"
baseurl: "/femurcc"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: default
show_excerpts: true

permalink: /:year/:month/:title:output_ext

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-sitemap

paginate: 10
paginate_path: /page:num/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: true
